### ISSUE TITLE
Error when downloading OSM

### ISSUE THREAD

**Issue by ItzSteveHuh** [stackTom/Ortho4XP_FSX_P3D#30]
After downloading the latest update, I get the following error after 256secs if the download times out.
Attempting to download OSM data from 32, -96.5 to 32.5, -96.0
        OSM server MAP rejected our query, new tentative in 2 sec...
        OSM server MAP rejected our query, new tentative in 4 sec...
        OSM server MAP rejected our query, new tentative in 8 sec...
        OSM server MAP rejected our query, new tentative in 16 sec...
        OSM server MAP rejected our query, new tentative in 32 sec...
        OSM server MAP rejected our query, new tentative in 64 sec...
        OSM server MAP rejected our query, new tentative in 128 sec...
        OSM server MAP rejected our query, new tentative in 256 sec...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "threading.py", line 864, in run
  File "O4_Tile_Utils.py", line 163, in build_tile_list
  File "O4_Vector_Map.py", line 44, in build_poly_file
  File "O4_Vector_Map.py", line 154, in include_scenproc
TypeError: a bytes-like object is required, not 'int'

**Comment by stackTom** [comment]
OSM servers sometimes block you temporarily if too many downloads have been attempted. I agree there should be a more elegant solution to this than to just error out. Might implement something eventually.
