### ISSUE TITLE
App does not launch

### ISSUE THREAD

**Issue by KS770426** [stackTom/Ortho4XP_FSX_P3D#31]
When Ortho4XP_v130.py is started, the following error appears:

Traceback (most recent call last):
  File "***\Ortho4XP_FSX_P3D\Ortho4XP_v130.py", line 11, in <module>
    import O4_Imagery_Utils as IMG
  File ".\src\O4_Imagery_Utils.py", line 34, in <module>
    import O4_ESP_Utils
  File ".\src\O4_ESP_Utils.py", line 8, in <module>
    from fast_image_mask import *
ImportError: DLL load failed: The specified module was not found.

I have installed Phyton 3.7.9 and the libs include *cp37* (successfully). The path specifications are correct. The paths in Ortho4XP.cfg have been adjusted. vs_BuildTools.exe version 2017 installed.

Maybe it is helpful to build a setup.exe file. Otherwise no one knows where and which dependencies are missing.

**Comment by stackTom** [comment]
There is an exe in the /dist folder which works out of the box, provided the correct visual studio redistributables are installed (please see readme).

If you want to run from the python script, I believe you need to place fast_image_mask.pyd file inside the /src folder as well as the main folder. Please try that, and let me know if it works. I will have to check my dev pc and see how I have it set up so running from Ortho4XP.py works.
